# Generated by Django 5.0.6 on 2024-07-27 23:24

import backend.shared.utils.validators_utils
import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_alter_user_options_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "system_modules",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[
                            backend.shared.utils.validators_utils.string_array_model_validator
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Extended Group",
                "verbose_name_plural": "Extended Groups",
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
