# Generated by Django 5.0.6 on 2024-07-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_extendedgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="ip_login",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
