# Generated by Django 5.0.6 on 2024-08-04 18:33

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("state", models.BooleanField(default=True)),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("CEDULA", "Cedula"),
                            ("RUC", "RUC"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        max_length=100,
                    ),
                ),
                ("identificacion", models.CharField(max_length=100)),
                ("razon_social", models.CharField(max_length=200)),
                ("commercial_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phone_1", models.CharField(max_length=20)),
                ("phone_2", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_3", models.CharField(blank=True, max_length=20, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("is_agente_retencion", models.BooleanField(default=False)),
                ("number_agente_retencion", models.IntegerField(default=0)),
                (
                    "razon_social_representante",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "identificacion_representante",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_representante",
                    models.EmailField(blank=True, max_length=200, null=True),
                ),
                (
                    "phone_representante",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("contador", models.CharField(blank=True, max_length=200, null=True)),
                ("genera_ats", models.BooleanField(default=False)),
                (
                    "schema_name",
                    models.CharField(
                        blank=True,
                        help_text="Ingrese un nombre de esquema",
                        max_length=60,
                        null=True,
                        verbose_name="Nombre del esquema",
                    ),
                ),
                (
                    "scheme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multicpy.scheme",
                        verbose_name="Esquema DB",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="multicpy.scheme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
