# Generated by Django 5.0.6 on 2024-08-04 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multicpy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("state", models.BooleanField(default=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=801, null=True),
                ),
                ("olt_quantity", models.IntegerField(verbose_name="Cantidad de OLT")),
                (
                    "has_electronic_billing",
                    models.BooleanField(
                        default=False, verbose_name="Tiene Facturación Electrónica"
                    ),
                ),
                (
                    "invoice_quantity",
                    models.IntegerField(default=0, verbose_name="Cantidad de Facturas"),
                ),
                (
                    "sales_ticket_quantity",
                    models.IntegerField(
                        default=0, verbose_name="Cantidad de Tickets de Venta"
                    ),
                ),
                (
                    "credit_note_quantity",
                    models.IntegerField(
                        default=0, verbose_name="Cantidad de Notas de Crédito"
                    ),
                ),
                (
                    "has_consumption_graphs",
                    models.BooleanField(
                        default=False, verbose_name="Tiene Gráficas de Consumo"
                    ),
                ),
                (
                    "has_monitoring",
                    models.BooleanField(default=False, verbose_name="Tiene Monitoreo"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Precio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="suscripcion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="multicpy.suscripcion",
                verbose_name="Suscripcion/Plan para cada empresa",
            ),
        ),
    ]
